# Generated by Django 6.0.2 on 2026-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatformCommission', '0001_initial'),
        ('accounts', '0004_alter_user_profile_image'),
        ('order', '0002_remove_order_delivery_fee_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='platformrevenue',
            index=models.Index(fields=['revenue_type'], name='PlatformCom_revenue_c73cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='platformrevenue',
            index=models.Index(fields=['created_at'], name='PlatformCom_created_663fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='platformrevenue',
            index=models.Index(fields=['seller'], name='PlatformCom_seller__9dd264_idx'),
        ),
        migrations.AddIndex(
            model_name='platformrevenue',
            index=models.Index(fields=['buyer'], name='PlatformCom_buyer_i_c1bf81_idx'),
        ),
    ]
