# Generated by Django 6.0.2 on 2026-02-09 19:03

import cloudinary_storage.storage
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='categories/')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Liter'), ('pcs', 'Pieces'), ('dozen', 'Dozen'), ('hali', 'Hali (4 pcs)')], default='kg', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Liter'), ('pcs', 'Pieces'), ('dozen', 'Dozen'), ('hali', 'Hali (4 pcs)')], default='kg', max_length=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('is_organic', models.BooleanField(default=False)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[800, 800], storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
