# Generated by Django 6.0.2 on 2026-02-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='nid_number',
            field=models.CharField(default=12, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='village',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
