# Generated by Django 6.0.2 on 2026-04-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='address_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='address_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
