# Generated by Django 6.0.2 on 2026-02-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_city_order_is_paid_order_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
