# Generated by Django 6.0.2 on 2026-04-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
