# Generated by Django 6.0.2 on 2026-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_email_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='buyer_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
