# Generated by Django 6.0.2 on 2026-04-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('hold', 'Hold Payment'), ('release', 'Release to Seller'), ('refund', 'Refund to Buyer'), ('platform_commission', 'Platform Commission')], max_length=20),
        ),
    ]
